"use client";
import Link from "next/link";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Bell, Building2, ChevronDown, FileText, Handshake, Home, LocateFixed, LogOut, Menu, MessageCircle, Package, Plus, Search, Send, Store, Target, Upload, UserRound, Users, X } from "lucide-react";
import { AcheFoodLogo } from "@/components/brand/achefood-logo";
import { createClient } from "@/lib/supabase/client";
import { MobileBottomNav } from "@/components/platform/mobile-bottom-nav";
type Row=Record<string,unknown>;
export type WorkspaceData={categories:Row[];products:Row[];opportunities:Row[];quotes:Row[];connections:Row[];conversations:Row[];messages:Row[]};
type CompanyProfile=Record<string,unknown>;
type Props={section:string;activePath:string;companyId:string;user:{id:string;name:string;firstName:string;lastName:string;phone:string;email:string;avatarUrl:string;accountType:string;companyName:string;company:CompanyProfile};data:WorkspaceData};
const nav=[[Home,"Início","/app/dashboard"],[Search,"Buscar produtos","/app/buscar"],[FileText,"Cotações","/app/cotacoes"],[Store,"Meus produtos","/app/produtos"],[Target,"Oportunidades","/app/oportunidades"],[Users,"Conexões","/app/conexoes"],[MessageCircle,"Mensagens","/app/mensagens"],[UserRound,"Perfil","/app/perfil"]] as const;
const labels:Record<string,[string,string]>={produtos:["Meus produtos","Gerencie o catálogo publicado pela sua empresa."],buscar:["Buscar produtos","Encontre produtos e fornecedores no AcheFood."],oportunidades:["Oportunidades","Publique demandas ou encontre novos negócios."],cotacoes:["Cotações","Acompanhe propostas enviadas e recebidas."],conexoes:["Conexões","Gerencie seus relacionamentos comerciais."],mensagens:["Mensagens","Converse com empresas conectadas."],perfil:["Meu perfil","Atualize seus dados pessoais e as informações da empresa."]};
const txt=(v:unknown)=>typeof v==="string"?v:""; const num=(v:unknown)=>Number(v??0); const obj=(v:unknown)=>((Array.isArray(v)?v[0]:v)??{}) as Row;
const rel=(v:unknown,key:string,fallback="—")=>txt(obj(v)[key])||fallback;
const money=(v:unknown,c="BRL")=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:c}).format(num(v));

export function PlatformWorkspace({section,activePath,companyId,user,data}:Props){
 const router=useRouter(),supabase=useMemo(()=>createClient(),[]); const [drawer,setDrawer]=useState(false),[form,setForm]=useState(false),[quoteFor,setQuoteFor]=useState<Row|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[query,setQuery]=useState(""); const [conversation,setConversation]=useState(txt(data.conversations[0]?.id)),[messages,setMessages]=useState(data.messages);
 const [searchRows,setSearchRows]=useState<Row[]>(data.products),[searching,setSearching]=useState(false),[radius,setRadius]=useState<number|null>(null),[origin,setOrigin]=useState<{lat:number;lng:number}|null>(()=>{const rawLat=user.company.latitude,rawLng=user.company.longitude,lat=Number(rawLat),lng=Number(rawLng);return rawLat!=null&&rawLng!=null&&Number.isFinite(lat)&&Number.isFinite(lng)?{lat,lng}:null});
 const [title,copy]=labels[section];
 useEffect(()=>{if(section!=="buscar")return;const timer=window.setTimeout(async()=>{setSearching(true);const {data:rows,error}=await supabase.rpc("search_marketplace_products",{search_text:query,origin_lat:origin?.lat??null,origin_lng:origin?.lng??null,radius_km:radius,result_limit:100});setSearching(false);if(error)setNotice(error.message);else setSearchRows(rows??[])},320);return()=>window.clearTimeout(timer)},[origin,query,radius,section,supabase]);
 function locate(){if(!navigator.geolocation)return setNotice("Geolocalização indisponível. Usando a localização cadastrada da empresa.");navigator.geolocation.getCurrentPosition(p=>{setOrigin({lat:p.coords.latitude,lng:p.coords.longitude});setNotice("Localização atualizada para esta busca.")},()=>setNotice("Não foi possível acessar sua localização. Usando o endereço cadastrado."),{enableHighAccuracy:false,timeout:8000,maximumAge:300000})}
 async function run(action:()=>PromiseLike<{error:{message:string}|null}>,success:string){setBusy(true);setNotice("");const {error}=await action();setBusy(false);if(error)return setNotice(error.message);setNotice(success);setForm(false);router.refresh()}
 async function logout(){await supabase.auth.signOut();router.replace("/login")}
 async function product(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),name=String(f.get("name"));const slug=`${name.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}-${Date.now().toString(36)}`;await run(async()=>supabase.from("products").insert({company_id:companyId,name,slug,description:String(f.get("description")||""),category_id:f.get("category_id")||null,sku:f.get("sku")||null,unit:f.get("unit"),price:Number(f.get("price")),min_order_quantity:Number(f.get("minimum")||1),status:f.get("status")}),"Produto salvo.")}
 async function opportunity(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),closes=String(f.get("closes_at")||"");await run(async()=>supabase.from("opportunities").insert({buyer_company_id:companyId,title:f.get("title"),description:f.get("description"),category_id:f.get("category_id")||null,delivery_city:f.get("city"),delivery_state:String(f.get("state")).trim().toUpperCase(),closes_at:closes?new Date(closes).toISOString():null,status:"open",published_at:new Date().toISOString()}),"Oportunidade publicada.")}
 async function status(table:string,id:unknown,value:string){const action=table==="connections"?()=>supabase.rpc("respond_to_connection",{target_connection:id,decision:value}):table==="quotes"?()=>supabase.rpc("respond_to_quote",{target_quote:id,decision:value}):()=>supabase.from(table).update({status:value}).eq("id",id);await run(action,"Status atualizado.")}
 async function connect(supplier:unknown){await run(async()=>supabase.from("connections").insert({buyer_company_id:companyId,supplier_company_id:supplier,initiated_by_company_id:companyId,status:"pending"}),"Solicitação enviada.")}
 async function quote(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!quoteFor)return;const f=new FormData(e.currentTarget),validUntil=String(f.get("valid_until")||"");await run(async()=>supabase.rpc("create_and_submit_quote",{target_opportunity:quoteFor.id,supplier_company:companyId,item_description:f.get("description"),item_quantity:Number(f.get("quantity")),item_unit:f.get("unit"),item_unit_price:Number(f.get("price")),quote_notes:f.get("notes")||"",quote_valid_until:validUntil?new Date(validUntil).toISOString():null}),"Cotação enviada.");setQuoteFor(null)}
 async function choose(id:string){setConversation(id);await supabase.rpc("mark_conversation_read",{target_conversation:id});const {data:rows,error}=await supabase.from("messages").select("id,conversation_id,sender_company_id,body,read_at,created_at").eq("conversation_id",id).order("created_at");if(error)setNotice(error.message);else setMessages(rows??[])}
 async function send(e:FormEvent<HTMLFormElement>){e.preventDefault();const input=e.currentTarget.elements.namedItem("body") as HTMLInputElement;if(!conversation||!input.value.trim())return;setBusy(true);const {data:row,error}=await supabase.from("messages").insert({conversation_id:conversation,sender_company_id:companyId,body:input.value.trim()}).select("id,conversation_id,sender_company_id,body,read_at,created_at").single();setBusy(false);if(error)return setNotice(error.message);setMessages(old=>[...old,row]);input.value=""}
 return <div className="dashboard-shell platform-shell"><aside className={drawer?"client-sidebar open":"client-sidebar"}><AcheFoodLogo/><Link href="/app/perfil" className="profile">{user.avatarUrl?<Image src={user.avatarUrl} alt="" width={42} height={42} unoptimized/>:<span>{user.name.slice(0,2).toUpperCase()}</span>}<b>{user.name}<small>{user.accountType}</small></b></Link><nav>{nav.map(([Icon,label,href])=><Link className={href===`/app/${section}`?"active":""} href={href} key={href}><Icon/>{label}</Link>)}</nav><button onClick={logout}><LogOut/> Sair</button></aside>{drawer&&<button className="drawer-backdrop" onClick={()=>setDrawer(false)}/>}<header className="client-top"><button onClick={()=>setDrawer(true)} aria-label="Abrir menu"><Menu/></button><div className="mobile-brand"><AcheFoodLogo/></div><span/><button aria-label="Notificações"><Bell/></button><Link href="/app/mensagens" aria-label="Mensagens"><MessageCircle/></Link><Link href="/app/perfil" className="avatar" aria-label="Abrir perfil">{user.avatarUrl?<Image src={user.avatarUrl} alt="" width={42} height={42} unoptimized/>:user.name.slice(0,2).toUpperCase()}</Link><ChevronDown className="desktop-only"/></header>
 <main className="dashboard-main platform-main"><header className="platform-heading"><div><span className="eyebrow">{user.companyName}</span><h1>{title}</h1><p>{copy}</p></div>{["produtos","oportunidades"].includes(section)&&<button className="af-btn af-btn-primary" onClick={()=>setForm(true)}><Plus/> {section==="produtos"?"Novo produto":"Nova oportunidade"}</button>}</header>{notice&&<div className="platform-notice" role="status">{notice}<button onClick={()=>setNotice("")}><X/></button></div>}
 {section==="buscar"&&<><div className="search-toolbar"><label className="catalog-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busque por produto, categoria ou fornecedor"/></label><label className="radius-field"><span>Distância</span><select value={radius??""} onChange={e=>setRadius(e.target.value?Number(e.target.value):null)}><option value="">Qualquer distância</option>{[2,5,10,20,50,100].map(km=><option value={km} key={km}>Até {km} km</option>)}</select></label><button className="locate-button" onClick={locate}><LocateFixed/> Usar minha localização</button></div>{searching?<SearchSkeleton/>:<ProductGrid rows={searchRows} own={companyId} connect={connect} radius={radius}/>}</>}{section==="perfil"&&<ProfilePanel user={user} companyId={companyId} busy={busy} setBusy={setBusy} setNotice={setNotice}/>} {section==="produtos"&&<ProductTable rows={data.products} status={status}/>} {section==="oportunidades"&&<OpportunityList rows={data.opportunities} companyId={companyId} quote={setQuoteFor}/>} {section==="cotacoes"&&<QuoteList rows={data.quotes} companyId={companyId} status={status}/>} {section==="conexoes"&&<ConnectionList rows={data.connections} companyId={companyId} status={status}/>} {section==="mensagens"&&<MessageCenter conversations={data.conversations} messages={messages} selected={conversation} companyId={companyId} busy={busy} choose={choose} send={send}/>}</main>
 {form&&<div className="modal-backdrop"><section className="platform-modal af-card" role="dialog" aria-modal="true"><button className="modal-close" onClick={()=>setForm(false)}><X/></button>{section==="produtos"?<ProductForm categories={data.categories} busy={busy} submit={product}/>:<OpportunityForm categories={data.categories} busy={busy} submit={opportunity}/>}</section></div>}
 {quoteFor&&<div className="modal-backdrop"><section className="platform-modal af-card" role="dialog" aria-modal="true"><button className="modal-close" onClick={()=>setQuoteFor(null)}><X/></button><QuoteForm opportunity={quoteFor} busy={busy} submit={quote}/></section></div>}<MobileBottomNav active={activePath} /></div>
}
function Empty({Icon,title,copy}:{Icon:typeof Package;title:string;copy:string}){return <div className="platform-empty"><Icon/><strong>{title}</strong><p>{copy}</p></div>}
function ProductGrid({rows,own,connect,radius}:{rows:Row[];own:string;connect:(id:unknown)=>void;radius:number|null}){if(!rows.length)return <Empty Icon={Search} title={radius?`Nenhum fornecedor encontrado em até ${radius} km`:"Nenhum produto encontrado"} copy="Aumente o raio, tente outro termo ou atualize sua localização."/>;return <div className="product-grid">{rows.map(r=><article className="af-card product-card" key={txt(r.id)}>{r.image_url?<Image src={txt(r.image_url)} alt="" width={480} height={290} unoptimized/>:<div className="product-placeholder"><Package/></div>}<small>{txt(r.category_name)||rel(r.categories,"name","Sem categoria")}</small><h2>{txt(r.name)}</h2><p>{txt(r.description)||"Produto disponível para cotação."}</p><span className="supplier-name">{txt(r.supplier_name)||rel(r.companies,"trade_name","Fornecedor")}</span><span>{[txt(r.supplier_city),txt(r.supplier_state)].filter(Boolean).join(" - ")||[rel(r.companies,"city",""),rel(r.companies,"state","")].filter(Boolean).join(" - ")}{r.distance_km!=null?` • ${num(r.distance_km).toLocaleString("pt-BR")} km`:""}</span>{r.company_id!==own&&<button className="af-btn af-btn-secondary" onClick={()=>connect(r.company_id)}><Handshake/> Conectar</button>}</article>)}</div>}
function SearchSkeleton(){return <div className="product-grid" aria-label="Carregando resultados">{[1,2,3].map(i=><div className="af-card product-card skeleton-card" key={i}><i/><b/><span/><span/></div>)}</div>}

function ProfilePanel({user,companyId,busy,setBusy,setNotice}:{user:Props["user"];companyId:string;busy:boolean;setBusy:(v:boolean)=>void;setNotice:(v:string)=>void}){
 const supabase=useMemo(()=>createClient(),[]); const router=useRouter();
 async function upload(file:File,kind:"avatar"|"logo"){if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>5*1024*1024){setNotice("Envie uma imagem JPG, PNG ou WebP de até 5 MB.");return null}const root=kind==="avatar"?`avatars/${user.id}`:`companies/${companyId}`,path=`${root}/${kind}-${Date.now()}.${file.name.split(".").pop()?.toLowerCase()||"jpg"}`;const {error}=await supabase.storage.from("profile-media").upload(path,file,{upsert:false,contentType:file.type});if(error){setNotice(error.message);return null}return supabase.storage.from("profile-media").getPublicUrl(path).data.publicUrl}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setNotice("");const f=new FormData(e.currentTarget),avatar=f.get("avatar") as File,logo=f.get("logo") as File;const avatarUrl=avatar?.size?await upload(avatar,"avatar"):user.avatarUrl;const logoUrl=logo?.size?await upload(logo,"logo"):txt(user.company.logo_url);const [{error:pError},{error:cError}]=await Promise.all([supabase.from("profiles").update({first_name:f.get("first_name"),last_name:f.get("last_name"),phone:f.get("phone"),avatar_url:avatarUrl||null}).eq("id",user.id),supabase.from("companies").update({legal_name:f.get("legal_name"),trade_name:f.get("trade_name"),cnpj:f.get("cnpj")||null,phone:f.get("company_phone")||null,cep:f.get("cep")||null,address_line:f.get("address_line")||null,neighborhood:f.get("neighborhood")||null,complement:f.get("complement")||null,city:f.get("city")||null,state:String(f.get("state")||"").toUpperCase()||null,logo_url:logoUrl||null}).eq("id",companyId)]);setBusy(false);if(pError||cError)return setNotice((pError||cError)?.message||"Não foi possível salvar.");setNotice("Perfil atualizado com sucesso.");router.refresh()}
 return <form className="profile-form" onSubmit={save}><section className="af-card profile-section"><h2>Dados pessoais</h2><div className="profile-media"><div className="profile-preview">{user.avatarUrl?<Image src={user.avatarUrl} alt="Avatar atual" width={76} height={76} unoptimized/>:<UserRound/>}</div><Field label="Foto de perfil"><input name="avatar" type="file" accept="image/jpeg,image/png,image/webp"/></Field></div><div className="form-grid"><Field label="Nome"><input name="first_name" defaultValue={user.firstName} required maxLength={80}/></Field><Field label="Sobrenome"><input name="last_name" defaultValue={user.lastName} required maxLength={100}/></Field><Field label="Telefone"><input name="phone" defaultValue={user.phone} maxLength={30}/></Field><Field label="E-mail"><input value={user.email} readOnly aria-describedby="email-help"/><small id="email-help">O e-mail de acesso só pode ser alterado pelo fluxo seguro de autenticação.</small></Field></div></section><section className="af-card profile-section"><h2>Dados da empresa</h2><div className="profile-media"><div className="profile-preview">{txt(user.company.logo_url)?<Image src={txt(user.company.logo_url)} alt="Logo atual" width={76} height={76} unoptimized/>:<Building2/>}</div><Field label="Logo da empresa"><input name="logo" type="file" accept="image/jpeg,image/png,image/webp"/></Field></div><div className="form-grid"><Field label="Razão social"><input name="legal_name" defaultValue={txt(user.company.legal_name)} required/></Field><Field label="Nome fantasia"><input name="trade_name" defaultValue={txt(user.company.trade_name)} required/></Field><Field label="CNPJ"><input name="cnpj" defaultValue={txt(user.company.cnpj)}/></Field><Field label="Telefone comercial"><input name="company_phone" defaultValue={txt(user.company.phone)}/></Field><Field label="CEP"><input name="cep" defaultValue={txt(user.company.cep)}/></Field><Field label="Endereço"><input name="address_line" defaultValue={txt(user.company.address_line)}/></Field><Field label="Bairro"><input name="neighborhood" defaultValue={txt(user.company.neighborhood)}/></Field><Field label="Complemento"><input name="complement" defaultValue={txt(user.company.complement)}/></Field><Field label="Cidade"><input name="city" defaultValue={txt(user.company.city)}/></Field><Field label="UF"><input name="state" defaultValue={txt(user.company.state)} maxLength={2}/></Field></div></section><button className="af-btn af-btn-primary profile-save" disabled={busy}>{busy?<><Upload/> Salvando…</>:"Salvar alterações"}</button></form>
}
function ProductTable({rows,status}:{rows:Row[];status:(t:string,id:unknown,s:string)=>void}){if(!rows.length)return <Empty Icon={Package} title="Seu catálogo está vazio" copy="Cadastre o primeiro produto para receber oportunidades."/>;return <div className="af-card platform-table-wrap"><table className="platform-table"><thead><tr><th>Produto</th><th>Categoria</th><th>Preço</th><th>Status</th><th>Ação</th></tr></thead><tbody>{rows.map(r=><tr key={txt(r.id)}><td><strong>{txt(r.name)}</strong><small>{txt(r.sku)||"Sem SKU"}</small></td><td>{rel(r.categories,"name")}</td><td>{money(r.price,txt(r.currency)||"BRL")} / {txt(r.unit)}</td><td><Tag value={txt(r.status)}/></td><td><button onClick={()=>status("products",r.id,r.status==="active"?"inactive":"active")}>{r.status==="active"?"Pausar":"Publicar"}</button></td></tr>)}</tbody></table></div>}
function OpportunityList({rows,companyId,quote}:{rows:Row[];companyId:string;quote:(row:Row)=>void}){if(!rows.length)return <Empty Icon={Target} title="Nenhuma oportunidade" copy="Publique uma demanda para receber propostas."/>;return <div className="item-list">{rows.map(r=><article className="af-card item-card" key={txt(r.id)}><div><Tag value={txt(r.status)}/><small>{rel(r.categories,"name","Demanda")}</small></div><h2>{txt(r.title)}</h2><p>{txt(r.description)}</p><footer><span>{txt(r.delivery_city)}, {txt(r.delivery_state)}</span>{r.buyer_company_id===companyId?<span>Publicada por sua empresa</span>:r.status==="open"?<button onClick={()=>quote(r)}>Enviar cotação</button>:<span>Encerrada</span>}</footer></article>)}</div>}
function QuoteList({rows,companyId,status}:{rows:Row[];companyId:string;status:(t:string,id:unknown,s:string)=>void}){if(!rows.length)return <Empty Icon={FileText} title="Nenhuma cotação" copy="Propostas enviadas e recebidas aparecerão aqui."/>;return <div className="item-list">{rows.map(r=>{const o=obj(r.opportunities),buyer=o.buyer_company_id===companyId;return <article className="af-card item-card" key={txt(r.id)}><div><Tag value={txt(r.status)}/><small>{buyer?"Recebida":"Enviada"}</small></div><h2>{txt(o.title)||"Cotação"}</h2><p>{txt(r.notes)||"Sem observações."}</p><footer><strong>{money(r.total_amount,txt(r.currency)||"BRL")}</strong>{buyer&&r.status==="submitted"&&<span className="inline-actions"><button onClick={()=>status("quotes",r.id,"accepted")}>Aceitar</button><button onClick={()=>status("quotes",r.id,"rejected")}>Recusar</button></span>}</footer></article>})}</div>}
function ConnectionList({rows,companyId,status}:{rows:Row[];companyId:string;status:(t:string,id:unknown,s:string)=>void}){if(!rows.length)return <Empty Icon={Users} title="Nenhuma conexão" copy="Encontre um fornecedor e envie uma solicitação."/>;return <div className="connection-list">{rows.map(r=>{const incoming=r.supplier_company_id===companyId&&r.status==="pending";return <article className="af-card connection-card" key={txt(r.id)}><span className="company-avatar"><Building2/></span><div><h2>{r.buyer_company_id===companyId?rel(r.supplier,"trade_name"):rel(r.buyer,"trade_name")}</h2><Tag value={txt(r.status)}/></div>{incoming&&<span className="inline-actions"><button onClick={()=>status("connections",r.id,"accepted")}>Aceitar</button><button onClick={()=>status("connections",r.id,"rejected")}>Recusar</button></span>}</article>})}</div>}
function MessageCenter({conversations,messages,selected,companyId,busy,choose,send}:{conversations:Row[];messages:Row[];selected:string;companyId:string;busy:boolean;choose:(id:string)=>void;send:(e:FormEvent<HTMLFormElement>)=>void}){if(!conversations.length)return <Empty Icon={MessageCircle} title="Nenhuma conversa" copy="Conversas são liberadas após uma conexão aceita."/>;return <section className="af-card message-center"><aside>{conversations.map(r=>{const c=obj(r.connections);return <button className={r.id===selected?"active":""} onClick={()=>choose(txt(r.id))} key={txt(r.id)}><span className="company-avatar"><Building2/></span><b>{c.buyer_company_id===companyId?rel(c.supplier,"trade_name"):rel(c.buyer,"trade_name")}</b></button>})}</aside><div className="message-thread"><div className="messages">{messages.map(r=><div className={r.sender_company_id===companyId?"message mine":"message"} key={txt(r.id)}>{txt(r.body)}<small>{new Date(txt(r.created_at)).toLocaleString("pt-BR")}</small></div>)}</div><form onSubmit={send}><input name="body" placeholder="Digite uma mensagem" maxLength={4000}/><button disabled={busy}><Send/></button></form></div></section>}
function Tag({value}:{value:string}){return <span className={`status ${value}`}>{value}</span>}; function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="form-field"><span>{label}</span>{children}</label>}
function ProductForm({categories,busy,submit}:{categories:Row[];busy:boolean;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <form onSubmit={submit}><h2>Novo produto</h2><div className="form-grid"><Field label="Nome"><input name="name" required maxLength={140}/></Field><Field label="SKU"><input name="sku" maxLength={60}/></Field><Field label="Categoria"><select name="category_id"><option value="">Sem categoria</option>{categories.map(c=><option key={txt(c.id)} value={txt(c.id)}>{txt(c.name)}</option>)}</select></Field><Field label="Unidade"><select name="unit"><option value="un">Unidade</option><option value="kg">Quilo</option><option value="cx">Caixa</option><option value="lt">Litro</option></select></Field><Field label="Preço"><input name="price" type="number" min="0" step=".01" required/></Field><Field label="Pedido mínimo"><input name="minimum" type="number" min=".001" step=".001" defaultValue="1"/></Field><Field label="Status"><select name="status"><option value="draft">Rascunho</option><option value="active">Publicado</option></select></Field><Field label="Descrição"><textarea name="description" maxLength={2000}/></Field></div><button className="af-btn af-btn-primary" disabled={busy}>{busy?"Salvando…":"Salvar produto"}</button></form>}
function OpportunityForm({categories,busy,submit}:{categories:Row[];busy:boolean;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <form onSubmit={submit}><h2>Nova oportunidade</h2><div className="form-grid"><Field label="Título"><input name="title" required maxLength={160}/></Field><Field label="Categoria"><select name="category_id"><option value="">Sem categoria</option>{categories.map(c=><option key={txt(c.id)} value={txt(c.id)}>{txt(c.name)}</option>)}</select></Field><Field label="Cidade"><input name="city" required/></Field><Field label="UF"><input name="state" maxLength={2} required/></Field><Field label="Prazo"><input name="closes_at" type="datetime-local"/></Field><Field label="Descrição"><textarea name="description" required maxLength={4000}/></Field></div><button className="af-btn af-btn-primary" disabled={busy}>{busy?"Publicando…":"Publicar oportunidade"}</button></form>}
function QuoteForm({opportunity,busy,submit}:{opportunity:Row;busy:boolean;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <form onSubmit={submit}><h2>Enviar cotação</h2><p className="muted">{txt(opportunity.title)}</p><div className="form-grid"><Field label="Descrição do item"><input name="description" required minLength={2} defaultValue={txt(opportunity.title)}/></Field><Field label="Quantidade"><input name="quantity" type="number" min=".001" step=".001" defaultValue="1" required/></Field><Field label="Unidade"><select name="unit"><option value="un">Unidade</option><option value="kg">Quilo</option><option value="cx">Caixa</option><option value="lt">Litro</option></select></Field><Field label="Preço unitário"><input name="price" type="number" min="0" step=".01" required/></Field><Field label="Validade"><input name="valid_until" type="datetime-local"/></Field><Field label="Observações"><textarea name="notes" maxLength={2000}/></Field></div><button className="af-btn af-btn-primary" disabled={busy}>{busy?"Enviando…":"Enviar cotação"}</button></form>}
