"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, BarChart3, Building2, CheckCircle2, ChevronLeft, ChevronRight, Download, Loader2, Package, Pencil, Plus, RefreshCw, Search, ShieldCheck, Trash2, Users, X } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type ModuleName = "empresas" | "usuarios" | "produtos" | "planos" | "relatorios";
type Row = Record<string, unknown> & { id: string };
type Reports = { totals?: Record<string, number>; new_in_period?: Record<string, number> };
type Field = { key: string; label: string; type?: "text" | "email" | "number" | "select" | "textarea" | "checkbox"; options?: string[]; required?: boolean };

const config: Record<Exclude<ModuleName,"relatorios">,{title:string;description:string;icon:typeof Building2;fields:Field[];columns:[string,string][];canCreate:boolean}> = {
  empresas:{title:"Empresas",description:"Cadastros, situação e dados operacionais das empresas.",icon:Building2,canCreate:true,columns:[["trade_name","Empresa"],["cnpj","CNPJ"],["city","Cidade"],["status","Status"]],fields:[{key:"legal_name",label:"Razão social",required:true},{key:"trade_name",label:"Nome fantasia",required:true},{key:"cnpj",label:"CNPJ"},{key:"phone",label:"Telefone"},{key:"city",label:"Cidade"},{key:"state",label:"UF"},{key:"status",label:"Status",type:"select",options:["pending","active","suspended","blocked"],required:true}]},
  usuarios:{title:"Usuários",description:"Perfis, papéis e situação de acesso à plataforma.",icon:Users,canCreate:false,columns:[["full_name","Usuário"],["email","E-mail"],["role","Papel"],["status","Status"]],fields:[{key:"full_name",label:"Nome completo",required:true},{key:"phone",label:"Telefone"},{key:"profile_type",label:"Perfil",type:"select",options:["buyer","supplier","both"]},{key:"status",label:"Status",type:"select",options:["active","suspended"]}]},
  produtos:{title:"Produtos",description:"Catálogo global, moderação e disponibilidade.",icon:Package,canCreate:true,columns:[["name","Produto"],["company_name","Empresa"],["sku","SKU"],["status","Status"]],fields:[{key:"company_id",label:"ID da empresa",required:true},{key:"name",label:"Nome",required:true},{key:"description",label:"Descrição",type:"textarea"},{key:"sku",label:"SKU"},{key:"unit",label:"Unidade",required:true},{key:"price",label:"Preço",type:"number"},{key:"status",label:"Status",type:"select",options:["draft","active","inactive","archived"],required:true}]},
  planos:{title:"Planos",description:"Preços, limites e publicação da matriz comercial.",icon:ShieldCheck,canCreate:true,columns:[["name","Plano"],["price_monthly","Mensalidade"],["product_limit","Produtos"],["is_active","Publicado"]],fields:[{key:"name",label:"Nome",required:true},{key:"slug",label:"Identificador (slug)",required:true},{key:"description",label:"Descrição",type:"textarea"},{key:"price_monthly",label:"Mensalidade",type:"number"},{key:"product_limit",label:"Limite de produtos",type:"number"},{key:"included_users",label:"Usuários incluídos",type:"number"},{key:"trial_available",label:"Teste gratuito disponível",type:"checkbox"},{key:"is_active",label:"Plano publicado",type:"checkbox"},{key:"is_featured",label:"Plano em destaque",type:"checkbox"}]},
};

const menu:[ModuleName,string,typeof Building2][]=[["empresas","Empresas",Building2],["usuarios","Usuários",Users],["produtos","Produtos",Package],["planos","Planos",ShieldCheck],["relatorios","Relatórios",BarChart3]];

function text(value:unknown){ if(value===null||value===undefined||value==="") return "—"; if(typeof value==="boolean") return value?"Sim":"Não"; return String(value); }
function tone(value:unknown){ const v=String(value); return ["active","published","ativo"].includes(v)?"success":["blocked","suspended","inactive","archived"].includes(v)?"danger":"warning"; }

export function AdminCrud({module,adminName}:{module:ModuleName;adminName:string}){
  const [rows,setRows]=useState<Row[]>([]),[reports,setReports]=useState<Reports|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[page,setPage]=useState(1),[total,setTotal]=useState(0);
  const [editing,setEditing]=useState<Row|null>(null),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[notice,setNotice]=useState("");
  const limit=12;
  const load=useCallback(async()=>{setLoading(true);setError("");try{const supabase=createClient();let result:{data:unknown;error:{message:string}|null};const common={search_term:query||null,page_limit:limit,page_offset:(page-1)*limit};if(module==="empresas")result=await supabase.rpc("admin_list_companies",{...common,status_filter:null});else if(module==="usuarios")result=await supabase.rpc("admin_list_users",{...common,status_filter:null});else if(module==="produtos")result=await supabase.rpc("admin_list_products",{...common,company_filter:null,status_filter:null});else if(module==="planos")result=await supabase.rpc("admin_list_plans");else{const end=new Date(),start=new Date();start.setDate(end.getDate()-30);result=await supabase.rpc("admin_get_reports",{period_start:start.toISOString(),period_end:end.toISOString()});}if(result.error)throw new Error(result.error.message);if(module==="relatorios"){const body=(result.data||{}) as Reports;setReports(body);const items=Object.entries(body.totals||{}).map(([id,value])=>({id,label:id,value}));setRows(items);setTotal(items.length);return;}const body=(result.data||{}) as {data?:Row[];items?:Row[];total?:number};const items=Array.isArray(result.data)?result.data as Row[]:body.data||body.items||[];setRows(items);setTotal(body.total??items.length);}catch(e){setError(e instanceof Error?e.message:"Erro inesperado.");}finally{setLoading(false)}},[module,page,query]);
  useEffect(()=>{const timer=setTimeout(load,query?300:0);return()=>clearTimeout(timer)},[load,query]);
  const cfg=module==="relatorios"?null:config[module];
  const pages=Math.max(1,Math.ceil(total/limit));
  const reportCards=useMemo(()=>rows.length?rows:[],[rows]);
  function begin(row?:Row){setEditing(row||null);setOpen(true);setError("");}
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const fd=new FormData(e.currentTarget);const payload:Record<string,unknown>=Object.fromEntries(fd.entries());cfg?.fields.forEach(f=>{if(f.type==="checkbox")payload[f.key]=fd.has(f.key);if(f.type==="number"&&payload[f.key]!=="")payload[f.key]=Number(payload[f.key])});try{const supabase=createClient();let error:{message:string}|null=null;if(module==="empresas")({error}=await supabase.rpc("admin_save_company",{target_company:editing?.id||null,company_data:payload}));else if(module==="usuarios")({error}=await supabase.rpc("admin_update_user",{target_user:editing?.id,profile_data:payload}));else if(module==="produtos")({error}=await supabase.rpc("admin_save_product",{target_product:editing?.id||null,product_data:payload}));else if(module==="planos"){const keys=["company_profile","catalog","products_limit","users_limit","csv_import","search_visibility","radius_search","buyer_contacts","opportunities","eu_tenho","analytics","commercial_page","search_highlight","support_level","basic_search","categories","supplier_view"];const features=(editing?.features as unknown[]||keys.map(feature_key=>({feature_key,enabled:["company_profile","basic_search","categories","supplier_view"].includes(feature_key),limit_value:feature_key==="products_limit"?Number(payload.product_limit||0):feature_key==="users_limit"?Number(payload.included_users||1):null,config_json:{label:"Não"}})));if(editing)({error}=await supabase.rpc("admin_save_plan",{target_plan:editing.id,plan_data:payload,features_data:features}));else ({error}=await supabase.rpc("admin_create_plan",{plan_data:payload,features_data:features}));}if(error)throw new Error(error.message);setOpen(false);setNotice("Alterações salvas e registradas na auditoria.");await load();}catch(e){setError(e instanceof Error?e.message:"Erro ao salvar.");}finally{setSaving(false)}}
  async function archive(row:Row){if(!confirm(`Arquivar ${text(row.name)}? O item deixará de aparecer no catálogo, mas continuará no histórico.`))return;setSaving(true);try{const {error}=await createClient().rpc("admin_archive_product",{target_product:row.id});if(error)throw new Error(error.message);setNotice("Produto arquivado com segurança.");await load();}catch(e){setError(e instanceof Error?e.message:"Erro ao arquivar.");}finally{setSaving(false)}}
  async function deactivatePlan(row:Row){if(!confirm(`Desativar o plano ${text(row.name)}? Assinaturas existentes serão preservadas.`))return;setSaving(true);try{const {error}=await createClient().rpc("admin_deactivate_plan",{target_plan:row.id});if(error)throw new Error(error.message);setNotice("Plano desativado e registrado na auditoria.");await load();}catch(e){setError(e instanceof Error?e.message:"Erro ao desativar o plano.");}finally{setSaving(false)}}
  function exportCsv(){const csvRows=[...Object.entries(reports?.totals||{}).map(([metric,value])=>({grupo:"totais",metrica:metric,valor:value})),...Object.entries(reports?.new_in_period||{}).map(([metric,value])=>({grupo:"novos_30_dias",metrica:metric,valor:value}))];const headers=["grupo","metrica","valor"] as const;const safe=(value:unknown)=>{const raw=text(value);const guarded=/^[=+\-@]/.test(raw)?`'${raw}`:raw;return `"${guarded.replaceAll('"','""')}"`};const csv=[headers.join(";"),...csvRows.map(r=>headers.map(h=>safe(r[h])).join(";"))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download=`achefood-relatorio-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
  return <div className="ac-shell"><aside className="ac-side"><Link href="/admin/dashboard" className="ac-back"><ArrowLeft/>Painel AcheFood</Link><nav aria-label="Módulos administrativos">{menu.map(([slug,label,Icon])=><Link key={slug} href={`/admin/${slug}`} className={slug===module?"active":""}><Icon/>{label}</Link>)}</nav></aside>
   <main className="ac-main"><header className="ac-top"><div><span>Super Administrador</span><b>{adminName}</b></div></header><div className="ac-content"><div className="ac-heading"><div>{cfg&&<cfg.icon/>}<div><h1>{cfg?.title||"Relatórios"}</h1><p>{cfg?.description||"Indicadores consolidados e exportação para análise."}</p></div></div><div className="ac-actions"><button className="ac-secondary" onClick={load}><RefreshCw/>Atualizar</button>{module==="relatorios"&&<button className="ac-primary" onClick={exportCsv}><Download/>Exportar CSV</button>}{cfg?.canCreate&&<button className="ac-primary" onClick={()=>begin()}><Plus/>Adicionar</button>}</div></div>
    {notice&&<div className="ac-notice" role="status"><CheckCircle2/>{notice}<button aria-label="Fechar aviso" onClick={()=>setNotice("")}><X/></button></div>}
    <section className="ac-card"><div className="ac-toolbar"><label><span className="sr-only">Buscar</span><Search/><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder={`Buscar em ${cfg?.title.toLowerCase()||"relatórios"}…`}/></label><span>{total} registro{total===1?"":"s"}</span></div>
     {loading?<div className="ac-state" role="status"><Loader2 className="spin"/><b>Carregando dados reais…</b></div>:error?<div className="ac-state error" role="alert"><b>Não foi possível carregar</b><p>{error}</p><button onClick={load}>Tentar novamente</button></div>:module==="relatorios"?<div className="ac-reports">{reportCards.length?reportCards.map(r=><article key={r.id}><BarChart3/><strong>{Number(r.value||0).toLocaleString("pt-BR")}</strong><span>{text(r.label).replaceAll("_"," ")}</span></article>):<div className="ac-state"><BarChart3/><b>Ainda não há indicadores consolidados.</b></div>}</div>:rows.length?<div className="ac-table-wrap"><table><thead><tr>{cfg!.columns.map(([,label])=><th key={label}>{label}</th>)}<th><span className="sr-only">Ações</span></th></tr></thead><tbody>{rows.map(row=><tr key={row.id}>{cfg!.columns.map(([key])=><td key={key}>{key==="status"||typeof row[key]==="boolean"?<span className={`ac-badge ${tone(row[key])}`}>{text(row[key])}</span>:text(row[key])}</td>)}<td><div className="ac-row-actions"><button aria-label="Editar registro" onClick={()=>begin(row)}><Pencil/></button>{module==="produtos"&&row.status!=="archived"&&<button className="danger" aria-label="Arquivar produto" onClick={()=>archive(row)}><Trash2/></button>}{module==="planos"&&Boolean(row.is_active)&&!Boolean(row.is_free)&&<button className="danger" aria-label="Desativar plano" onClick={()=>deactivatePlan(row)}><Trash2/></button>}</div></td></tr>)}</tbody></table></div>:cfg&&<div className="ac-state"><cfg.icon/><b>Nenhum registro encontrado</b><p>Ajuste a busca ou adicione o primeiro registro.</p></div>}
     {!loading&&!error&&module!=="relatorios"&&<footer className="ac-pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}><ChevronLeft/>Anterior</button><span>Página {page} de {pages}</span><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Próxima<ChevronRight/></button></footer>}
    </section></div></main>
   {open&&cfg&&<div className="ac-modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="ac-overlay" onClick={()=>!saving&&setOpen(false)} aria-label="Fechar formulário"/><form onSubmit={save}><header><div><h2 id="modal-title">{editing?"Editar":"Adicionar"} {cfg.title.toLowerCase()}</h2><p>Preencha os dados obrigatórios.</p></div><button type="button" onClick={()=>setOpen(false)} aria-label="Fechar"><X/></button></header><div className="ac-form">{cfg.fields.map(field=><label key={field.key} className={field.type==="checkbox"?"check":""}>{field.type==="checkbox"?<><input name={field.key} type="checkbox" defaultChecked={Boolean(editing?.[field.key])}/><span>{field.label}</span></>:<><span>{field.label}{field.required&&" *"}</span>{field.type==="textarea"?<textarea name={field.key} required={field.required} defaultValue={text(editing?.[field.key])==="—"?"":text(editing?.[field.key])}/>:field.type==="select"?<select name={field.key} required={field.required} defaultValue={text(editing?.[field.key])==="—"?field.options?.[0]:text(editing?.[field.key])}>{field.options?.map(o=><option key={o}>{o}</option>)}</select>:<input name={field.key} type={field.type||"text"} step={field.type==="number"?"0.01":undefined} required={field.required} defaultValue={text(editing?.[field.key])==="—"?"":text(editing?.[field.key])}/>}</>}</label>)}</div>{error&&<p className="ac-form-error" role="alert">{error}</p>}<footer><button type="button" className="ac-secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="ac-primary" disabled={saving}>{saving&&<Loader2 className="spin"/>}Salvar alterações</button></footer></form></div>}
  </div>
}
