"use client";
import Link from "next/link";
import {useSearchParams} from "next/navigation";
import {useState} from "react";
import {createClient,isSupabaseConfigured} from "@/lib/supabase/client";
const profileTypes:Record<string,string>={comprador:"buyer",fornecedor:"supplier",ambos:"both"};
export function SignupForm(){const params=useSearchParams();const[loading,setLoading]=useState(false);const[message,setMessage]=useState("");const[pendingEmail,setPendingEmail]=useState("");const[cooldown,setCooldown]=useState(false);const defaultType=params.get("tipo")||"comprador";
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setMessage("");const f=new FormData(e.currentTarget),email=String(f.get("email")).trim().toLowerCase();if(f.get("password")!==f.get("confirm")){setMessage("As senhas não coincidem.");setLoading(false);return}try{const{data,error}=await createClient().auth.signUp({email,password:String(f.get("password")),options:{data:{first_name:f.get("firstName"),last_name:f.get("lastName"),profile_type:profileTypes[String(f.get("type"))]??"buyer"},emailRedirectTo:`${location.origin}/auth/callback?next=${encodeURIComponent("/onboarding")}`}});if(error)throw error;if(data.session){location.href="/onboarding";return}setPendingEmail(email);setMessage("Conta criada. Enviamos um link de confirmação para seu e-mail. Verifique também a caixa de spam.")}catch{setMessage("Não foi possível concluir o cadastro agora. Se este e-mail já possui uma conta, entre ou recupere sua senha.")}finally{setLoading(false)}}
async function resend(){if(!pendingEmail||cooldown)return;setCooldown(true);const{error}=await createClient().auth.resend({type:"signup",email:pendingEmail,options:{emailRedirectTo:`${location.origin}/auth/callback?next=${encodeURIComponent("/onboarding")}`}});setMessage(error?"Não foi possível reenviar agora. Aguarde um minuto e tente novamente.":"Enviamos um novo link. Verifique sua caixa de entrada e spam.");window.setTimeout(()=>setCooldown(false),60000)}
return <div className="auth-card signup-card af-card"><h2>Crie sua conta <span>grátis</span></h2><p>Comece a encontrar e gerar oportunidades B2B.</p><form onSubmit={submit}><div className="form-grid"><label>Nome<input required name="firstName" autoComplete="given-name"/></label><label>Sobrenome<input required name="lastName" autoComplete="family-name"/></label><label className="full">E-mail<input required type="email" name="email" autoComplete="email"/></label><label className="full">Perfil<select name="type" defaultValue={defaultType}><option value="comprador">Comprador</option><option value="fornecedor">Fornecedor</option><option value="ambos">Comprador + Fornecedor</option></select></label><label>Senha<input required minLength={8} type="password" name="password" autoComplete="new-password"/><small>Use pelo menos 8 caracteres.</small></label><label>Confirmar senha<input required minLength={8} type="password" name="confirm" autoComplete="new-password"/></label><label className="full"><input required type="checkbox" name="terms"/> Li e aceito os <Link href="/termos">Termos de Uso</Link> e a <Link href="/privacidade">Política de Privacidade</Link>.</label></div>{message&&<div role="status" className="auth-notice">{message}</div>}{pendingEmail&&<button type="button" className="text-button" onClick={resend} disabled={cooldown}>{cooldown?"Aguarde para reenviar":"Não recebeu o e-mail? Reenviar confirmação"}</button>}{!isSupabaseConfigured()&&<div className="auth-notice">O formulário está pronto; configure o Supabase para persistir o cadastro.</div>}<button className="af-btn af-btn-primary submit" disabled={loading}>{loading?"Criando conta...":"Criar conta"}</button></form><div className="signup-copy">Já tem uma conta?<Link href="/login">Entrar</Link> · <Link href="/recuperar-senha">Recuperar senha</Link></div></div>}
